from __future__ import annotations

import json
from pathlib import Path
from typing import Any
import numpy as np

from flora.core.config import APEX, BUD_DORMANT, FLOWER, FLORAL_AXIS, INTERNODE
from flora.core.spatial import UP_VECTOR, quat_rotate
from flora.core.state import PlantState
from flora.io.snapshot import snapshot


def _generate_cylinder_geometry(
    start: np.ndarray,
    end: np.ndarray,
    r_start: float,
    r_end: float,
    segments: int = 8,
) -> tuple[np.ndarray, np.ndarray, list[list[int]]]:
    axis = end - start
    length = np.linalg.norm(axis)
    if length < 1e-7:
        return np.empty((0, 3)), np.empty((0, 3)), []

    z_dir = axis / length
    # Find perpendicular vector for coordinate frame
    if abs(z_dir[0]) < 0.9 and abs(z_dir[1]) < 0.9:
        ref = np.array([0.0, 0.0, 1.0])
    else:
        ref = np.array([1.0, 0.0, 0.0])

    x_dir = np.cross(z_dir, ref)
    x_dir /= np.linalg.norm(x_dir)
    y_dir = np.cross(z_dir, x_dir)

    angles = np.linspace(0, 2.0 * np.pi, segments, endpoint=False)
    cos_a = np.cos(angles)
    sin_a = np.sin(angles)

    verts = []
    normals = []

    # Bottom ring vertices and normals
    for c, s in zip(cos_a, sin_a):
        rad_dir = c * x_dir + s * y_dir
        verts.append(start + rad_dir * r_start)
        normals.append(rad_dir)

    # Top ring vertices and normals
    for c, s in zip(cos_a, sin_a):
        rad_dir = c * x_dir + s * y_dir
        verts.append(end + rad_dir * r_end)
        normals.append(rad_dir)

    faces = []
    for i in range(segments):
        next_i = (i + 1) % segments
        # Quad face (2 triangles: i, next_i, next_i + segments; i, next_i + segments, i + segments)
        faces.append([i, next_i, next_i + segments])
        faces.append([i, next_i + segments, i + segments])

    return np.array(verts), np.array(normals), faces


def _generate_sphere_geometry(
    center: np.ndarray,
    radius: float,
    lat_segments: int = 4,
    lon_segments: int = 8,
) -> tuple[np.ndarray, np.ndarray, list[list[int]]]:
    verts = []
    normals = []
    faces = []

    for lat in range(lat_segments + 1):
        theta = lat * np.pi / lat_segments
        sin_t = np.sin(theta)
        cos_t = np.cos(theta)

        for lon in range(lon_segments):
            phi = lon * 2.0 * np.pi / lon_segments
            sin_p = np.sin(phi)
            cos_p = np.cos(phi)

            n = np.array([sin_t * cos_p, sin_t * sin_p, cos_t])
            verts.append(center + n * radius)
            normals.append(n)

    for lat in range(lat_segments):
        for lon in range(lon_segments):
            next_lon = (lon + 1) % lon_segments
            v0 = lat * lon_segments + lon
            v1 = lat * lon_segments + next_lon
            v2 = (lat + 1) * lon_segments + lon
            v3 = (lat + 1) * lon_segments + next_lon

            faces.append([v0, v1, v3])
            faces.append([v0, v3, v2])

    return np.array(verts), np.array(normals), faces


def export_obj(
    state_or_snap: PlantState | dict[str, Any],
    out_path: str | Path | None = None,
    radial_segments: int = 8,
) -> str:
    """Generate Wavefront .OBJ mesh string and optionally persist to file."""
    if isinstance(state_or_snap, PlantState):
        snap = snapshot(state_or_snap)
    else:
        snap = state_or_snap

    n = int(snap["n"])
    if n == 0:
        content = "# Wavefront OBJ generated by Flora Engine\n# 0 vertices\n"
        if out_path:
            Path(out_path).write_text(content, encoding="utf-8")
        return content

    pos = snap["position"]
    orient = snap["orientation"]
    length = snap["internode_length"]
    radius = snap["radius"]
    node_type = snap["node_type"]
    alive = snap["alive"]

    all_verts: list[np.ndarray] = []
    all_normals: list[np.ndarray] = []
    all_faces: list[list[int]] = []
    vert_offset = 1

    lines = [
        "# Wavefront OBJ exported from Flora Simulation Engine",
        "o Plant",
    ]

    for i in range(n):
        if not alive[i]:
            continue

        nt = int(node_type[i])
        start = pos[i]
        L = float(length[i])
        r = float(radius[i]) if radius[i] > 1e-6 else 0.005

        if L > 1e-6:
            dir_vec = quat_rotate(orient[i : i + 1], UP_VECTOR)[0]
            end = start + dir_vec * L
            v, norm, f = _generate_cylinder_geometry(
                start, end, r, r * 0.9, segments=radial_segments
            )
            if v.shape[0] > 0:
                for idxs in f:
                    all_faces.append([idx + vert_offset for idx in idxs])
                all_verts.extend(v)
                all_normals.extend(norm)
                vert_offset += v.shape[0]

        if nt == int(FLOWER):
            dir_vec = quat_rotate(orient[i : i + 1], UP_VECTOR)[0]
            flower_pos = start + dir_vec * max(L, 0.005)
            v_sp, norm_sp, f_sp = _generate_sphere_geometry(
                flower_pos, max(r * 2.0, 0.015), lat_segments=4, lon_segments=6
            )
            if v_sp.shape[0] > 0:
                for idxs in f_sp:
                    all_faces.append([idx + vert_offset for idx in idxs])
                all_verts.extend(v_sp)
                all_normals.extend(norm_sp)
                vert_offset += v_sp.shape[0]

    for v in all_verts:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")

    for norm in all_normals:
        lines.append(f"vn {norm[0]:.6f} {norm[1]:.6f} {norm[2]:.6f}")

    for f in all_faces:
        lines.append(f"f {f[0]}//{f[0]} {f[1]}//{f[1]} {f[2]}//{f[2]}")

    content = "\n".join(lines) + "\n"
    if out_path:
        Path(out_path).write_text(content, encoding="utf-8")
    return content


def export_gltf(
    state_or_snap: PlantState | dict[str, Any],
    out_path: str | Path | None = None,
) -> dict[str, Any]:
    """Generate glTF 2.0 scene dictionary and optionally persist to JSON file."""
    if isinstance(state_or_snap, PlantState):
        snap = snapshot(state_or_snap)
    else:
        snap = state_or_snap

    n = int(snap["n"])
    nodes_data = []

    pos = snap["position"]
    orient = snap["orientation"]
    radius = snap["radius"]
    node_type = snap["node_type"]
    woodiness = snap["woodiness"]
    length = snap["internode_length"]
    alive = snap["alive"]

    for i in range(n):
        if not alive[i]:
            continue
        nodes_data.append(
            {
                "name": f"Node_{i}",
                "translation": pos[i].tolist(),
                "rotation": [orient[i][1], orient[i][2], orient[i][3], orient[i][0]],
                "extras": {
                    "node_type": int(node_type[i]),
                    "radius": float(radius[i]),
                    "length": float(length[i]),
                    "woodiness": float(woodiness[i]),
                },
            }
        )

    gltf: dict[str, Any] = {
        "asset": {"version": "2.0", "generator": "Flora Simulation Engine"},
        "scenes": [{"name": "FloraScene", "nodes": list(range(len(nodes_data)))}],
        "scene": 0,
        "nodes": nodes_data,
    }

    if out_path:
        Path(out_path).write_text(json.dumps(gltf, indent=2), encoding="utf-8")

    return gltf
